% Produced by CVXGEN, 2015-09-15 18:35:38 -0400.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
PgMax = params.PgMax;
PgMin = params.PgMin;
Pg_N_avg = params.Pg_N_avg;
Pg_N_init = params.Pg_N_init;
Thetag_N_avg = params.Thetag_N_avg;
Vg_N_avg = params.Vg_N_avg;
c0 = params.c0;
c1 = params.c1;
c2 = params.c2;
ones = params.ones;
rho = params.rho;
ug_N = params.ug_N;
vg_N = params.vg_N;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable Pg;
  variable Thetag(11, 1);

  minimize(c2*square(Pg) + c1*Pg + c0 + (rho/2)*sum(square(ones*Pg - Pg_N_init + Pg_N_avg + ug_N) + square(Thetag - Vg_N_avg - Thetag_N_avg + vg_N)));
  subject to
    PgMin <= Pg;
    Pg <= PgMax;
cvx_end
vars.Pg = Pg;
vars.Thetag = Thetag;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
